logging:
  level:
    com.netflix.discovery.TimedSupervisorTask: "OFF"
    org.springframework.security: DEBUG 

app:
  oauth2:
    accesstokenUrl: http://apigateway:9999/uaa/oauth/token
    common:
      clientId: test-service
      secret: '{cipher}7d4462e15eef9f82cf23cb9cda46f98fe25ca42e2826e04bd03e4c8feecefe25'
      scope: operation


jwtKeyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuekEV9p8ylVaLqiVr9zCU+veKoeY+18wMDeos/pb5bd1R3Pw/xcMVhB6fCHbTqVXtQzJc4anWBlHNzewQZV1zkJvRrVD2OdUZ4HZfbYLvmRvEAIjPbybEMjlYVM9/hZjBK0SqEgcfQ0IKOJONXJoJRqDDpD826G6wkW67xdE83nbRFZaCzIwVuJP9cwETdoObAAgkDQos/5xIQy69mQbuI4/9vmTtsY3hF7pSvK3uIvFr9wLsDg83aPKm6o/pnrU9z2NfFxjbFIUBnWv6z7UUs5UHGGwqCjiRFlBOGR5NcZ0Clzg4w8akX77AlhJioqdvn8N5Nuv3p7EmRGTDQdKkwIDAQAB
          -----END PUBLIC KEY-----
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 5
     preferIpAddress: true
